# script to load marine boundaries
# Author: Lotte Pohl

# source(paste0(dir_path, "/functions.R"))
paste0("C:/Users/lotte.pohl/Documents/github_repos/MasterThesis_LottePohl/01_code/06_functions/functions.R") %>% source()

BPNS <- load_data(filestring = "BPNS", folder = path_boundaries)
Bergen_op_Zoom <- load_data(filestring = "Bergen_op_Zoom", folder = path_boundaries)
Neeltje_Jans <- load_data(filestring = "Neeltje_Jans", folder = path_boundaries)
Cap_de_la_Hague <- load_data(filestring = "Cap_de_la_Hague", folder = path_boundaries)
Vlissingen <- load_data(filestring = "Vlissingen", folder = path_boundaries)
Norwich <- load_data(filestring = "Norwich", folder = path_boundaries)
Schelde_boundaries <- load_data(filestring = "Schelde_boundaries", folder = path_boundaries)
Belgium <- load_data(filestring = "Belgium", folder = path_boundaries)
Netherlands <- load_data(filestring = "Netherlands", folder = path_boundaries)
English_channel <- load_data(filestring = "English_channel", folder = path_boundaries)
Hurd_deep <- load_data(filestring = "Hurd_deep", folder = path_boundaries)
Dutch_EEZ <- load_data(filestring = "Dutch_EEZ", folder = path_boundaries)
French_EEZ <- load_data(filestring = "French_EEZ", folder = path_boundaries)
UK_EEZ <- load_data(filestring = "UK_EEZ", folder = path_boundaries)
UK <- load_data(filestring = "UK", folder = path_boundaries)
Europe <- load_data(filestring = "Europe", folder = path_boundaries)
France <- load_data(filestring = "France", folder = path_boundaries)
North_sea <- load_data(filestring = "North_sea", folder = path_boundaries)
Northern_North_Sea <- load_data(filestring = "Northern_North_Sea", folder = path_boundaries)
Southern_North_Sea <- load_data(filestring = "Southern_North_Sea", folder = path_boundaries)
Eastern_Scheldt_boundaries <- load_data(filestring = "Eastern_Scheldt_boundaries", folder = path_boundaries)
Western_Scheldt_boundaries <- load_data(filestring = "Western_Scheldt_boundaries", folder = path_boundaries)
Schelde_boundaries <- load_data(filestring = "Schelde_boundaries", folder = path_boundaries)
Zoetelande <- load_data(filestring = "Zoetelande", folder = path_boundaries)
Dishoek <- load_data(filestring = "Dishoek", folder = path_boundaries)
east_anglia <- load_data(filestring = "east_anglia", folder = path_boundaries)

# save_data(data = Dutch_EEZ, folder = path_boundaries)
# save_data(data = Europe, folder = path_boundaries)
# save_data(data = BPNS, folder = path_boundaries)
# save_data(data = Northern_North_Sea, folder = path_boundaries)
# save_data(data = Southern_North_Sea, folder = path_boundaries)
# save_data(data = Eastern_Scheldt_boundaries, folder = path_boundaries)
# save_data(data = Western_Scheldt_boundaries, folder = path_boundaries)
# save_data(data = Schelde_boundaries, folder = path_boundaries)
# save_data(data = Belgium, folder = path_boundaries)
# save_data(data = Netherlands, folder = path_boundaries)
# save_data(data = English_channel, folder = path_boundaries)
# save_data(data = Hurd_deep, folder = path_boundaries)
# save_data(data = North_sea, folder = path_boundaries)
# save_data(data = Zoetelande, folder = path_boundaries)
# save_data(data = Dishoek, folder = path_boundaries)


coastline <- st_read(paste0(path_boundaries, "ne_10m_coastline.shp"))

bbox_coastline <- c(xmin = -0.33, ymin = 49.5, xmax = 6, ymax = 54)
coastline <- crop_geom(coastline, bbox_coastline)
coastline_BE <- coastline$geometry[2]
new_point <- st_point(c(5.95, 49.39))
coastline_BE_poly <- st_linestring(rbind(st_coordinates(coastline_BE)[, c(1, 2)], st_coordinates(new_point)))


rm(bbox_coastline, new_point)
